### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by viniciusbezvieira** [lokeshkandala/ngx-rangeslider#1]
Just installed and... -> https://prnt.sc/km3rqh

my angular version is 6.0.8

**Comment by dudipsh** [comment]
@viniciosyals  did you fix the issue?

**Comment by viniciusbezvieira** [comment]
no, I tried...

**Comment by dudipsh** [comment]
@viniciosyals 
"ng2-nouislider": "^1.7.12",
try this one...

**Comment by lokeshkandala-zz** [comment]
@viniciosyals i've updated the package to  latest angular version(>6).
