### ISSUE TITLE
got an error after install and use

### ISSUE THREAD

**Issue by harellevy** [lokeshkandala/ngx-rangeslider#2]
in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-rangeslider-component/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by lokeshkandala-zz** [comment]
it is peer dependencies problem.can you check your package.json @angular/* versions with node_modules/ngx-rangeslider-component/package.json @angular/* versions. Try using version 1.0.5 for <= ng5.2.0 and 1.0.6 for >ng 5.2.0

**Comment by upender15** [comment]
Even I have the same issue I am using 1.0.6 version and my angular version is
 "dependencies": {
    "@angular/animations": "6.0.7",
    "@angular/common": "6.0.7",
    "@angular/compiler": "6.0.7",
    "@angular/core": "6.0.7"
}
 "peerDependencies": {
    "@angular/common": "6.0.1",
    "@angular/core": "6.0.7",
    "@angular/forms": "6.0.1"
  }
 "devDependencies": {
    "@angular-devkit/build-angular": "0.6.8",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "6.0.1"
}

**Comment by ohabash** [comment]
`npm uninstall ngx-rangeslider` is the only fix for ng7?
