### ISSUE TITLE
after install, and use

### ISSUE THREAD

**Issue by juilacoco** [lokeshkandala/ngx-rangeslider#5]
Hi, 
when use the range-slider as tag, it seem cannot bind ngModel, 
the issue says'Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'range-slider'.
1. If 'range-slider' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'range-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message....

is there any wrong here? have already checked  the dependencies, not  block there.

**Comment by juilacoco** [comment]
thanks!

**Comment by lokeshkandala-zz** [comment]
import and Include CUSTOM_ELEMENTS_SCHEMA in the **providers** array of respective module.
